---
# defaults file for ansible-common
log_dir: /var/log/druid
conf_dir: "{{ installation_dir }}/conf"
extensions_dir: "{{ installation_dir }}/extensions"
package_temp_dir: "/tmp/{{ druid_package_name }}-bin.tar.gz"
installation_dir: "{{ druid_base_dir }}/{{ druid_package_name}}"

#druid configurations directory
data_base_dir: "{{ default_base_dir }}/druid_data"
segment_cache_location: "{{ data_base_dir }}/data"
indexer_task_baseDir: "{{ data_base_dir }}/task"
#druid_indexer_task_hadoopWorkingPath: "/druid/{{ druid_environment }}/druid-indexing"

#druid metrics properties.
metrics_port: 2003
metrics_host: "{{ groups['cluster_druid_metadata_db'] | first }}"
metrics_white_list_location: "{{ conf_dir }}/whiteListMap.json"
graphite_emitter_archive: "resources/graphite-emitter-extensions-{{ druid_version }}.tar.gz"
druid_parquet_archive: "resources/druid-parquet-extensions-{{ druid_version }}.tar.gz"
druid_hdfs_storage_archive: "resources/druid-hdfs-storage-{{ druid_version }}.tar.gz"
druid_hadoop_dependencies_archive: "resources/hadoop-dependencies-{{ druid_version }}.tar.gz"
druid_indexing_hadoop_jar: "druid-indexing-hadoop-{{ druid_version }}.jar"
druid_indexing_hadoop_jar_path: "resources/{{ druid_indexing_hadoop_jar }}"

## added for supporting 0.13.0-incubating version too in the code.
druid_download_url: "{{ apache_druid_download_url if druid_package_type == 'apache' else io_druid_download_url }}"
druid_package_name: "{{ apache_druid_package_name if druid_package_type == 'apache' else io_druid_package_name }}"