- name: Install setuptools
  yum:
    name:
      - python-setuptools
      - epel-release
    state: latest
    update_cache: yes

- name: Install pip
  yum:
    name: python-pip
    state: latest

- name: Install supervisor
  pip:
    name: supervisor

- name: Ensure supervisor conf directory exits
  file:
    path: /etc/supervisor.d
    state: directory

- name: Ensure supervisor log conf exists
  file:
    path: /var/log/supervisord/
    state: directory
    mode: 0777

- name: Copy over supervisord init
  template:
    src: supervisord_init.sh
    dest: /etc/init.d/supervisor
    mode: 0777

- name: Copy over default supervisord config
  template:
    src: default_supervisord.conf
    dest: /etc/supervisord.conf
    mode: 0755

- name: Add supervisor as service
  shell: chkconfig --add supervisor; chkconfig supervisor on;

- name: Start supervisord
  service:
    name: supervisor
    state: started

