- name: Check if druid base directory exists.
  stat:
    path: "{{ druid_base_dir }}"
  register: d_base_dir

- name: Create druid base directory.
  file:
    mode: 0755
    state: directory
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    path: "{{ druid_base_dir }}"
  when: d_base_dir.stat.exists == False

- name: Check if druid has already been downloaded and unpacked
  stat:
    path: "{{ installation_dir }}"
  register: d_installation_dir

- include: install.yml
  when: d_installation_dir.stat.exists == False
  tags:
    - install

- include: configure.yml
  tags:
    - configure
